apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: leaderboards-deployment
spec:
  selector:
    matchLabels:
      app: leaderboards
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: leaderboards
    spec:
      containers:
      - name: leaderboards
        image: ancina/leaderboards:latest
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP

      livenessProbe:
        tcpSocket:
          port: 8084
        initialDelaySeconds: 15
        periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: leaderboards
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: leaderboards
